A Tensor in PyTorch is a multi-dimensional array that can be used for various mathematical operations and computations, similar to arrays in other programming languages. PyTorch is a popular open-source machine learning library that provides support for tensors as a fundamental data structure. Tensors in PyTorch are designed to work efficiently on both CPUs and GPUs, making them a key component for building and training neural networks and other machine learning models.

Tensors can have different dimensions, such as scalars (0-dimensional tensors), vectors (1-dimensional tensors), matrices (2-dimensional tensors), and higher-dimensional arrays. These dimensions are often referred to as axes or ranks.

PyTorch provides functionalities to create, manipulate, and perform operations on tensors. You can create tensors using various functions like torch.tensor(), torch.zeros(), torch.ones(), torch.rand(), and more. Once you have tensors, you can perform arithmetic operations, element-wise operations, matrix multiplications, and various other mathematical computations on them.

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
x = torch.empty(1)
print (x)

tensor([7.0065e-45])


In [4]:
y = torch.empty(2, 2)
print (y)

tensor([[0., 0.],
        [0., 0.]])


In [5]:
z = torch.empty(2, 2, 3)
print (z)

tensor([[[1.1112e-38, 9.5511e-39, 1.0102e-38],
         [1.0286e-38, 1.0194e-38, 9.6429e-39]],

        [[9.2755e-39, 9.1837e-39, 9.3674e-39],
         [1.0745e-38, 1.0653e-38, 9.5510e-39]]])


In [6]:
a = torch.ones(1, 3)
print (a)
print (a.dtype)

tensor([[1., 1., 1.]])
torch.float32


In [7]:
b = torch.ones(1, 3, dtype=torch.float16)
print (b)
print (b.dtype)
print (b.size())

tensor([[1., 1., 1.]], dtype=torch.float16)
torch.float16
torch.Size([1, 3])


In [8]:
c = torch.tensor ([[1,2,3], [4,5,6]])
print (c)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
x = torch.rand(2, 3)
y = torch.rand (2, 3)
z = x + y
print (z)
p = torch.add(x, y)
print (p)

tensor([[0.7286, 0.5584, 0.9868],
        [0.5161, 1.5801, 1.6526]])
tensor([[0.7286, 0.5584, 0.9868],
        [0.5161, 1.5801, 1.6526]])


In [10]:
a = torch.sub (x, y)
b = torch.mul (x, y)
c = torch.div (x,y)
print (a , b , c)

tensor([[-0.3874,  0.4530, -0.9277],
        [-0.2526,  0.1424,  0.2840]]) tensor([[0.0952, 0.0266, 0.0283],
        [0.0506, 0.6191, 0.6626]]) tensor([[0.3057, 9.5998, 0.0308],
        [0.3428, 1.1982, 1.4150]])


In [11]:
a.add_(1)

tensor([[0.6126, 1.4530, 0.0723],
        [0.7474, 1.1424, 1.2840]])

In [12]:
s = b.numpy()
s

array([[0.09519114, 0.02664176, 0.02825891],
       [0.05064746, 0.61908835, 0.6625693 ]], dtype=float32)

In [13]:
import torch

# Creating tensors
scalar_tensor = torch.tensor(5)  # Scalar (0-dimensional tensor)
vector_tensor = torch.tensor([1, 2, 3])  # Vector (1-dimensional tensor)
matrix_tensor = torch.tensor([[1, 2], [3, 4]])  # Matrix (2-dimensional tensor)

# Arithmetic operations
result = vector_tensor + 2  # Adding 2 to each element
print(result)  # Output: tensor([3, 4, 5])

# Element-wise operations
elementwise_product = vector_tensor * vector_tensor
print(elementwise_product)  # Output: tensor([1, 4, 9])

# Matrix multiplication
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[2, 0], [1, 3]])
matrix_product = torch.mm(matrix_a, matrix_b)
print(matrix_product)  # Output: tensor([[ 4,  6], [10, 12]])


tensor([3, 4, 5])
tensor([1, 4, 9])
tensor([[ 4,  6],
        [10, 12]])
