* requires_grad attribute for Tensors

torch.autograd is PyTorch’s automatic differentiation engine that powers neural network training .The autograd package provides automatic differentiation for all operations on Tensors. To tell PyTorch that we want the gradient, we have to set requires_grad=True. With this attribute set, all operations on the tensor are tracked in the computational graph.



In [25]:
import torch

In [26]:
x = torch.randn (3, requires_grad=True)
print (x)

tensor([ 1.1817, -0.7596,  1.1233], requires_grad=True)


In [27]:
y = x+2
print (y)

tensor([3.1817, 1.2404, 3.1233], grad_fn=<AddBackward0>)


In [28]:
z = y*y*2
z = z.mean()
print (z)

tensor(14.2776, grad_fn=<MeanBackward0>)


In [29]:
z.backward() #dz/dx
print (x.grad)

tensor([4.2422, 1.6539, 4.1644])


In [38]:
b = torch.tensor(3., requires_grad=True)
print(b)

tensor(3., requires_grad=True)


In [39]:
y = 3*b*b + 4*b + 2
print (y)

tensor(41., grad_fn=<AddBackward0>)


In [40]:
y.backward() # Derivative of 3*b*b + 4*b + 2 is, 6b+4

In [41]:
print (b.grad) # 6b+4 is 6*3+4 = 22

tensor(22.)


# Turn Gradient Calculation off

In [42]:
a = torch.tensor (2., requires_grad=True)
print (a)

tensor(2., requires_grad=True)


In [43]:
a = a.requires_grad_(False)
print (a)

tensor(2.)


In [44]:
#another way
a = a.detach()
print (a)

tensor(2.)


# Gradient accumulation

In [47]:
x = torch.tensor(5., requires_grad=True)
for epoch in range (3):
    y = 3*x**2 + 4*x + 2
    y.backward()
    print(x.grad)
   

tensor(34.)
tensor(68.)
tensor(102.)


Gradients are adding up. To avoid this we use grad.zero_()

In [48]:
x = torch.tensor(5., requires_grad=True)
for epoch in range (3):
    y = 3*x**2 + 4*x + 2
    y.backward()
    print(x.grad)
    x.grad.zero_()

tensor(34.)
tensor(34.)
tensor(34.)
