In [1]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
# 0) Prepare data
bc = datasets.load_breast_cancer()
X, y = bc.data, bc.target
print (X, y)

n_samples, n_features = X.shape
print (n_samples, n_features)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [3]:
print (X_train, X_test)

[[1.288e+01 1.822e+01 8.445e+01 ... 1.096e-01 2.582e-01 8.893e-02]
 [1.113e+01 2.244e+01 7.149e+01 ... 6.413e-02 3.169e-01 8.032e-02]
 [1.263e+01 2.076e+01 8.215e+01 ... 1.105e-01 2.226e-01 8.486e-02]
 ...
 [1.247e+01 1.860e+01 8.109e+01 ... 1.015e-01 3.014e-01 8.750e-02]
 [1.822e+01 1.870e+01 1.203e+02 ... 1.325e-01 3.021e-01 7.987e-02]
 [1.272e+01 1.378e+01 8.178e+01 ... 6.343e-02 2.369e-01 6.922e-02]] [[1.167e+01 2.002e+01 7.521e+01 ... 8.120e-02 3.206e-01 8.950e-02]
 [1.080e+01 9.710e+00 6.877e+01 ... 4.603e-02 2.090e-01 7.699e-02]
 [1.245e+01 1.641e+01 8.285e+01 ... 1.342e-01 3.231e-01 1.034e-01]
 ...
 [1.327e+01 1.476e+01 8.474e+01 ... 1.001e-01 2.027e-01 6.206e-02]
 [1.343e+01 1.963e+01 8.584e+01 ... 1.160e-01 2.884e-01 7.371e-02]
 [2.742e+01 2.627e+01 1.869e+02 ... 2.625e-01 2.641e-01 7.427e-02]]


In [4]:
print (y_train, y_test) 

[1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1
 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 1 1
 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1
 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 0 1
 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 1 1
 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1
 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 1 1 0 0 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1 1 1
 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 1 0 1 1 0 1
 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 0 1
 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 0 0 0
 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 0 1 0 1 0 1] [1 1 1 1 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1
 

In [5]:
# scale
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
print (X_train)
print (X_test)

[[-0.36180827 -0.26521011 -0.31715702 ... -0.07967528 -0.52798733
   0.2506337 ]
 [-0.8632675   0.71560604 -0.85646012 ... -0.76980239  0.44312729
  -0.20987332]
 [-0.4334453   0.32513895 -0.41286667 ... -0.06601541 -1.1169427
   0.0329492 ]
 ...
 [-0.479293   -0.17689018 -0.45697634 ... -0.20261414  0.18670009
   0.17414996]
 [ 1.16835876 -0.15364809  1.17466524 ...  0.26789258  0.19828067
  -0.23394164]
 [-0.40765597 -1.29715887 -0.42826344 ... -0.78042674 -0.88036793
  -0.80355834]]
[[-0.70853151  0.15314749 -0.70166016 ... -0.51072015  0.50433894
   0.28112023]
 [-0.95782838 -2.24311189 -0.9696472  ... -1.0445176  -1.34193688
  -0.38797883]
 [-0.48502396 -0.68589193 -0.38373765 ...  0.29369456  0.54569817
   1.02456363]
 ...
 [-0.2500545  -1.06938639 -0.30508928 ... -0.22386283 -1.44616213
  -1.18651192]
 [-0.20420679  0.06250334 -0.25931509 ...  0.01746159 -0.02836788
  -0.56341008]
 [ 3.80460157  1.60577805  3.94608399 ...  2.24098526 -0.43037955
  -0.5334584 ]]


In [7]:
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

y_train = y_train.view(y_train.shape[0], 1)
y_test = y_test.view(y_test.shape[0], 1)

In [8]:
print (X_train , y_train)

tensor([[-0.3618, -0.2652, -0.3172,  ..., -0.0797, -0.5280,  0.2506],
        [-0.8633,  0.7156, -0.8565,  ..., -0.7698,  0.4431, -0.2099],
        [-0.4334,  0.3251, -0.4129,  ..., -0.0660, -1.1169,  0.0329],
        ...,
        [-0.4793, -0.1769, -0.4570,  ..., -0.2026,  0.1867,  0.1741],
        [ 1.1684, -0.1536,  1.1747,  ...,  0.2679,  0.1983, -0.2339],
        [-0.4077, -1.2972, -0.4283,  ..., -0.7804, -0.8804, -0.8036]]) tensor([[1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [9]:
print (X_test, y_test)

tensor([[-0.7085,  0.1531, -0.7017,  ..., -0.5107,  0.5043,  0.2811],
        [-0.9578, -2.2431, -0.9696,  ..., -1.0445, -1.3419, -0.3880],
        [-0.4850, -0.6859, -0.3837,  ...,  0.2937,  0.5457,  1.0246],
        ...,
        [-0.2501, -1.0694, -0.3051,  ..., -0.2239, -1.4462, -1.1865],
        [-0.2042,  0.0625, -0.2593,  ...,  0.0175, -0.0284, -0.5634],
        [ 3.8046,  1.6058,  3.9461,  ...,  2.2410, -0.4304, -0.5335]]) tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
      

In [10]:
# 1) Model
# Linear model f = wx + b , sigmoid at the end
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

model = Model(n_features)
print (model)

Model(
  (linear): Linear(in_features=30, out_features=1, bias=True)
)


In [11]:
# 2) Loss and optimizer
num_epochs = 100
learning_rate = 0.01
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [12]:
# 3) Training loop
for epoch in range(num_epochs):
    # Forward pass and loss
    y_pred = model(X_train)
    loss = criterion(y_pred, y_train)

    # Backward pass and update
    loss.backward()
    optimizer.step()

    # zero grad before new step
    optimizer.zero_grad()

    if (epoch+1) % 10 == 0:
        print(f'epoch: {epoch+1}, loss = {loss.item():.4f}')

epoch: 10, loss = 0.5463
epoch: 20, loss = 0.4580
epoch: 30, loss = 0.4002
epoch: 40, loss = 0.3592
epoch: 50, loss = 0.3283
epoch: 60, loss = 0.3041
epoch: 70, loss = 0.2844
epoch: 80, loss = 0.2680
epoch: 90, loss = 0.2542
epoch: 100, loss = 0.2422


In [13]:
with torch.no_grad():
    y_predicted = model(X_test)
    y_predicted_cls = y_predicted.round()
    acc = y_predicted_cls.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy: {acc.item():.4f}')

accuracy: 0.8860
